### ISSUE TITLE
WoopsaClientSubscription_Thread never ends

### ISSUE THREAD

**Issue by mgnslndh** [woopsa-protocol/Woopsa#18]
I use WoopsaClient from a WPF application and when I have shutdown my last window there are still woopsa threads running. This only happens when I have registered for subscription using the method or the Change event on the WoopsaProperty. I am disposing the WoopsaClient.

**Comment by fabien-chevalley** [comment]
Hi, I encountered similar problems. I have to update woopsa to version 1.1.3 and correctly dispose client and each subscriptions.
I attached a small wrapper that I use, I hope it can help...

[CommunicationClient.txt](https://github.com/woopsa-protocol/Woopsa/files/254396/CommunicationClient.txt)

**Comment by francoisbirling** [comment]
Thank you for your feedback. I checked this issue and updated threads and resources disposal. Seems to work fine now within my unit tests.
Please get the latest source code version and let me know if the problem is resolved with your application.

**Comment by mgnslndh** [comment]
Ok, I will check again with the source code version. I actually debugged some unit tests and I could not reproduce the problem. Sounds promising! Any plans for a new nuget release?

**Comment by fabien-chevalley** [comment]
I released a new package with latest modifications.

**Comment by mgnslndh** [comment]
I have updated to the latest nuget but I still have the problem. I am currently debugging the issue using [Undisposed.Fody](https://github.com/ermshiperete/undisposed-fody) and I have four undisposed woopsa objects and 2 undisposed woopsa properties at application shutdown. This is a bit strange because I should not miss to dispose any object. I will look into this some more.

However, while in the debugger playing around I suddenly got an exception thrown from one of the threads still alive:

`System.ObjectDisposedException: Safe handle has been closed`

```
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Set()
   at Woopsa.WoopsaSubscriptionChannel.newSubscription_Publish(Object sender, PublishEventArgs e) in C:\Users\Documents\Source\Woopsa\Sources\DotNet\Woopsa\Services\SubscriptionService\WoopsaSubscriptionChannel.cs:line 75
   at Woopsa.WoopsaSubscription.DoPublish() in C:\Users\Documents\Source\Woopsa\Sources\DotNet\Woopsa\Services\SubscriptionService\WoopsaSubscription.cs:line 175
   at Woopsa.WoopsaSubscription._publishTimer_Elapsed(Object sender, EventArgs e) in C:\Users\Documents\Source\Woopsa\Sources\DotNet\Woopsa\Services\SubscriptionService\WoopsaSubscription.cs:line 104
   at Woopsa.LightWeightTimer.OnElapsed() in C:\Users\Documents\Source\Woopsa\Sources\DotNet\Woopsa\Utils\LightWeightTimer.cs:line 86
   at Woopsa.LightWeightTimer.Execute(Object obj) in C:\Users\Documents\Source\Woopsa\Sources\DotNet\Woopsa\Utils\LightWeightTimer.cs:line 76
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

It seems to me that they wake up and find out they have been disposed. So, that makes me believe that their Dispose() method do get called but they don't wake up immediately. Perhaps the `LightWeightTimer` is not shut down correctly.

I will see if I can dig up some more on this.

**Comment by mgnslndh** [comment]
Ok, this last comment could be totally wrong. This exception might have happened in another instance of Visual Studio where the WoopsaDemoClient & WoopsaDemoServer were running :) Yep, I think so.

**Comment by mgnslndh** [comment]
Ok, case closed. Everything is working fine now. Found the last objects and properties not being disposed. Woopsa working as expected!

Great work you guys have put into this library! Finally a modern library for "tag based" communication! OPC is really a pain to work with.
